name: Deploy Static HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create /var/www/html if not exists
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
          "sudo mkdir -p /var/www/html && sudo chown -R \$(whoami):\$(whoami) /var/www/html"

      - name: Deploy HTML files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/
