name: Deploy Static HTML to EC2

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing changes to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for this workflow.

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem  # Ensure key permissions are set correctly

      # Step 3: Create target directory on EC2 if it doesn't exist
      - name: Create /var/www/html directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo mkdir -p /var/www/html && sudo chown -R \$(whoami):\$(whoami) /var/www/html"

      # Step 4: Deploy files to EC2 using rsync
      - name: Deploy HTML files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

      # Step 5: Restart Apache (httpd) to apply changes
      - name: Restart Apache (httpd)
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl restart httpd"  # Restart Apache web server
