name: Test Popup

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Show Notice (echo)
        run: echo "::notice title=Hello World::🎉 This is a test notice!"

      - name: Show Error (echo)
        run: echo "::error title=Oops Something Went Wrong::🚨 This is a test error popup!"
